title: ejrx
description: "personal site"
# url: "http://ejrx.github.io"
url: "http://localhost:4000"
github_username: ejrx
email: ejrx@outlook.com
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
highlighter: pygments
